// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivu.Data.Models;

public partial class RefreshToken
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Token { get; set; }

    public DateTime? ExpiresTime { get; set; }

    public bool? IsExpired { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int CreateBy { get; set; }

    public DateTime? RevokedTime { get; set; }

    public int RevokedBy { get; set; }

    public string ReplaceByToken { get; set; }

    public bool? IsActive { get; set; }

    public virtual User User { get; set; }
}