// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Vivu.Data.Models;

public partial class User
{
    public int Id { get; set; }

    public int Role { get; set; }

    public string Fullname { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string UserName { get; set; }

    public string PasswordHash { get; set; }

    public string ConcurencyStamp { get; set; }

    public string Avatar { get; set; }

    public bool? Gender { get; set; }

    public DateTime? BirthDate { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();
}